### PR TITLE
Changed abandoned composer requirement

### PR DESCRIPTION
**Pull request by i-xperts**
Hi basz!

Instead of commenting Issue #8, I've just changed it and pr it here.

### CODE REVIEW

**Comment by basz** [comment]
thanks. 

Sorry, i don't have time to contribute to this package at the moment, but ill merge PR's if you got them ;-)

**Comment by i-xperts** [comment]
No Prob!
Therefore there are PR's!

**Comment by gabrielsomoza** [comment]
Thanks for this guys! Is there a release coming soon that we could use to benefit from it?

**Comment by basz** [comment]
I will do that ASAP

**Comment by basz** [comment]
x-mas presents,.. released 0.2.2

**Comment by gabrielsomoza** [comment]
Thanks @basz !

**Pull request merged**
