### PR TITLE
Apply PHP 8 support

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by basz** [comment]
hi, great to see some still uses this oldy...

Could you update this matrix too? https://github.com/basz/zf-oauth2-doctrine-mutatetablenames/blob/master/.travis.yml#L14

please add 7.3 and 8 

hhvm is deprecated. what about pre 7.3?

**Comment by samsonasik** [comment]
I personally think hhvm can be removed, and use php ^7.3|~8.0 only for next.

**Comment by basz** [comment]
let do ^7.3|~8.0 then... thx abdul!

**Comment by samsonasik** [comment]
updated.

**Comment by basz** [comment]
travis fails ... (does not show here it seems)

https://api.travis-ci.org/v3/job/754427406/log.txt

**Comment by samsonasik** [comment]
it seems need to update to laminas, I will try do that.

**Comment by samsonasik** [comment]
`api-skeletons/zf-oauth2-doctrine` seems no longer maintained, how about using a fork ?

**Comment by basz** [comment]
Sure... However, personally I'm not using this or that library anymore and not interested in maintaining it... You could do that and I can make you an admin maintainer of this package (or even transfer it)...

**Comment by samsonasik** [comment]
make me admin is ok, I just don't have full knowledge about this module, I probably will need your help if I found trouble in the future, just let me know what I can do, thank you ;)

**Comment by samsonasik** [comment]
Thank you for giving me access 👍

**Comment by basz** [comment]
sure. please take lead. hope this package is still useful to you... thx

**Comment by samsonasik** [comment]
@basz it currently still uses travis.org, could you migrate it to travis.com ? Thank you

**Comment by basz** [comment]
I think I just did that.

**Comment by samsonasik** [comment]
merged and released 1.0.0 https://github.com/basz/zf-oauth2-doctrine-mutatetablenames/releases/tag/1.0.0

**Pull request merged**
