### PR TITLE
Added entities names to config to ensure that all tables will be renamed

### PR DESCRIPTION
**Pull request by renatopeterman**
Some tables were not being renamed. Specifying the entities names in configuration file fix the problem.

### CODE REVIEW

**Comment by basz** [comment]
Are you sure you didn't miss something. I don't see how this addition would help solve (as [eventually](https://github.com/basz/zf-oauth2-doctrine-mutatetablenames/blob/master/src/EventListener/MutateTableNamesSubscriberFactory.php#L21) this array is being merged with the config from zf-oauth2-doctrine).

All my tables (incl join tables) are renamed fine without this fix. 

Which tables aren't renamed properly in your case? Could you dump the [mapping](https://github.com/basz/zf-oauth2-doctrine-mutatetablenames/blob/master/src/EventListener/MutateTableNamesSubscriberFactory.php#L21) after the merge. (both with and without this patch)

**Comment by renatopeterman** [comment]
Hi Bas,

I'm using the latest version of [zf-oauth2-doctrine](https://github.com/TomHAnderson/zf-oauth2-doctrine) with enable_default_entities param true.
The following tables were not being renamed:

* Scope_OAuth2
* PublicKey_OAuth2
* RefreshTokenToScope_OAuth2
* Jti_OAuth2
* Jwt_Outh
* RefreshTokenToScope_OAuth2
* AuthorizationCodeToScope_OAuth2 	Procurar
* ClientToScope_OAuth2

Checking the zf-oauth2-doctrine [configuration file](https://github.com/TomHAnderson/zf-oauth2-doctrine/blob/master/config/oauth2.doctrine-orm.global.php.dist), I noticed that the above entities were not mapped in dynamic_mapping key, so, when the MutateTableNamesSubscriber loadClassMetadata  method is called some entity names are blank. Including the entity names in mutatetablenames key solves the problem, but I don't know if it is the best solution.

**Comment by basz** [comment]
It seems are using an outdated configuration in your autoload directory as currently the dynamic_mapping defined within zf-oauth2-doctrine does contain the entities FQCN's.

example [client_entity](https://github.com/TomHAnderson/zf-oauth2-doctrine/blob/master/config/oauth2.doctrine-orm.global.php.dist#L25)

**Comment by renatopeterman** [comment]
Maybe, I will check that. 
But why Scope, PublicKey, Jwt and Jti entities are not present in dynamic_mapping ?

**Comment by basz** [comment]
you are correct! I have a more entries in my own autoload config file. 

I will check with maintainer of 'zf-oauth2-doctrine' to see if we should fix it here or there... thanks

**Comment by renatopeterman** [comment]
Ok, thanks!

**Comment by TomHAnderson** [comment]
Dynamic mapping is for the User entity.  The entities listed here do not contain a reference to user except through client, so no dynamic mapping is necessary.  Using this module to rename those tables is just fine, however.

**Pull request merged**
